// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx_r-_-Op8MG7167iqd6KQr35EyzQW3Pk',
    appId: '1:974514078256:web:0ae0d9d1fea124d35523f5',
    messagingSenderId: '974514078256',
    projectId: 'foodly-cb51c',
    authDomain: 'foodly-cb51c.firebaseapp.com',
    storageBucket: 'foodly-cb51c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnTx0qnMRIYTyvUPU0eI4lA-1ec6b_Ugg',
    appId: '1:974514078256:android:e6a69ae7c8c4da035523f5',
    messagingSenderId: '974514078256',
    projectId: 'foodly-cb51c',
    storageBucket: 'foodly-cb51c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg9VAXuoUKi4dMX1tzrB7GEctmI2P2ZaI',
    appId: '1:974514078256:ios:b9dffa1b8395b8fe5523f5',
    messagingSenderId: '974514078256',
    projectId: 'foodly-cb51c',
    storageBucket: 'foodly-cb51c.firebasestorage.app',
    iosBundleId: 'com.example.foodly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg9VAXuoUKi4dMX1tzrB7GEctmI2P2ZaI',
    appId: '1:974514078256:ios:b9dffa1b8395b8fe5523f5',
    messagingSenderId: '974514078256',
    projectId: 'foodly-cb51c',
    storageBucket: 'foodly-cb51c.firebasestorage.app',
    iosBundleId: 'com.example.foodly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx_r-_-Op8MG7167iqd6KQr35EyzQW3Pk',
    appId: '1:974514078256:web:0fa38c761bdb721e5523f5',
    messagingSenderId: '974514078256',
    projectId: 'foodly-cb51c',
    authDomain: 'foodly-cb51c.firebaseapp.com',
    storageBucket: 'foodly-cb51c.firebasestorage.app',
  );
}
